# Change these first
owner: hemdesignstudio # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Hem B2C
    url: https://hem.com/

  - name: Hem B2C EU
    url: https://hem.com/en-eu/

  - name: Hem B2C US
    url: https://hem.com/en-us/

  - name: Hem B2C CA
    url: https://hem.com/en-ca/

  - name: Hem B2B
    url: https://pro.hem.com/

  - name: Hem B2B EU 
    url: https://pro.hem.com/en-eu/

  - name: Hem B2B US 
    url: https://pro.hem.com/en-us/

  - name: Hem B2C UK 
    url: https://pro.hem.com/en-gb/

  - name: Hem Pro Signup
    url: https://pro-signup.hem.com/

  - name: Hem Commerce
    url: https://commerce.hem.com/api/v1/health/

status-website:
  cname: status.hem.com
  publish: true
  apiBaseUrl: https://api.github.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
